name: CI

on: [push, pull_request]

env:
  npm_config_engine_strict: true
  MISE_IDIOMATIC_VERSION_FILE_ENABLE_TOOLS: 'node,pnpm'

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:

    - uses: actions/checkout@v7
    - name: Setup mise
      uses: jdx/mise-action@v5

    - name: Set up environment
      run: mkdir cdk.tmp
      
    - run: pnpm ci
    - run: pnpm run testsynth
    - run: pnpm run test
    # don't run the actual deploy in the CI, but run everything up to here to get the best idea of whether it works
