name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    # checkout a dependent project
    - uses: actions/checkout@v2
      with:
        repository: tstibbs/cloud-core
        path: 'cloud-core' # will resolve to /home/runner/work/smart-home-integration/smart-home-integration/cloud-core

    # checkout 'this' project
    - uses: actions/checkout@v2
      with:
        path: 'smart-home-integration' # will resolve to /home/runner/work/smart-home-integration/smart-home-integration/smart-home-integration

    - uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install python dependencies
      run: pip install cfn-lint

    - run: npm ci
      working-directory: smart-home-integration
    - run: npm run build
      working-directory: smart-home-integration
    - run: npm run test
      working-directory: smart-home-integration
    - run: npm run package
      working-directory: smart-home-integration
    # don't run the actual deploy in the CI, but run everything up to here to get the best idea of whether it works
