name: CI

on: [push, pull_request]

env:
  npm_config_engine_strict: true

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:

    - uses: actions/checkout@v4
    - uses: jdx/mise-action@v4

    - name: Set up environment
      run: mkdir cdk.tmp
      
    - run: pnpm ci
    - run: pnpm run testsynth
    - run: pnpm run test
    # don't run the actual deploy in the CI, but run everything up to here to get the best idea of whether it works
